### ISSUE TITLE
Active tabs don't have different color

### ISSUE THREAD

**Issue by wizexplorer** [easonwong-de/White-Sur-Firefox-Theme-MacOS#11]
![image](https://github.com/easonwong-de/White-Sur-Firefox-Theme-MacOS/assets/93021399/c673ac4a-669d-40f7-b83f-cfc15c954267)
As you can see, I cannot tell which tab is active and which is inactive

**Comment by easonwong-de** [comment]
Hi. I noticed that it happens on Windows. Now it should have been fixed with the newest update. Please click “Code” and “Download ZIP” on the repository’s main page to get the latest patch.

**Comment by wizexplorer** [comment]
Hi, thanks for the update! I'm not sure if this is how it should have worked but the only difference it made was highlight the text of the selected tab - its background color is still the same:
![image](https://github.com/easonwong-de/White-Sur-Firefox-Theme-MacOS/assets/93021399/c623e056-b4db-4612-be7e-45e1361bd96c)
Although this works as well 👍

**Comment by easonwong-de** [comment]
Hello. Under the Adaptive Tab Bar Colour settings, You may want to set the toolbar background to at least one tick to make the active tab have a different colour.
![Screenshot 2024-01-21 at 23 42 50](https://github.com/easonwong-de/White-Sur-Firefox-Theme-MacOS/assets/16183548/ae96de53-db14-4782-8e9c-fa837af4623a)

**Comment by wizexplorer** [comment]
Thanks, that worked!
